import Footer from './components/Footer'
import FooterWrapper from './components/FooterWrapper'
import Header from './components/Header'
import PageWrapper from './components/PageWrapper'
import './globals.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({ subsets: ['latin'], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={`dark:bg-[#341931] bg-white dark:text-white ${poppins.className}`}>
        <PageWrapper>
          <Header />
          {children}
        </PageWrapper>
        <FooterWrapper /> 
        </body>
    </html>
  )
}
